name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        description: Specify release version

jobs:
  restructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create calculator folder, move files, and add __init__.py
      run: |
        mkdir calculator
        touch calculator/__init__.py
        mv calculator.py calculator/
        mv printer calculator/
        touch calculator/printer/__init__.py

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release-version }}
        release_name: ${{ github.event.inputs.release-version }}
        draft: false
        prerelease: false
